- name: understand vars preference
  hosts: local
  connection: local

# 5. play are executing
  vars: 
    GREETING: "Hello from play"

# 3. Files are executing
  vars_files:
  - course.yaml

# 4. Prompt are executing
  vars_prompt:
  - name: GREETING 
    prompt: Please enter the greeting
    private: false

  tasks:
  - name: print the greeting

# 2 .TASK executing
    vars:
      GREETING: "Hello from TASK"


    ansible.builtin.debug:
      msg: "{{ GREETING }}"


#  1. command line or args
#  2. Task
#  3. File
#  4. prompt
#  5. play
#  6. inventory