- name: loops
  hosts: local
  connection: local
  tasks:
   - name: print names
     ansible.builtin,debug:
      msg: "Hello, {{ item }}" # here item is a reserved keyword
     loop:
      - Suresh
      - Ramesh
      - Joseph
      - Raheem
